apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: #{Namespace}
resources:
#- namespace.yaml
- octopetshop-database-job.yaml
- octopetshop-loadbalancer.yaml
- octopetshop-productservice-cluster-ip-service.yaml
- octopetshop-productservice-deployment.yaml
- octopetshop-shoppingcart-cluster-ip-service.yaml
- octopetshop-shoppingcartservice-deployment.yaml
- octopetshop-sql-deployment.yaml
- octopetshop-sqlserver-cluster-ip-service.yaml
- octopetshop-web-cluster-ip-service.yaml
- octopetshop-web-deployment.yaml

secretGenerator:
  - name: database-credentials
    literals:
    - sa-password="#{Project.SQLServer.SA.Password}"
    - connectionstring="Data Source=octopetshop-sqlserver-cluster-ip-service;Initial Catalog=OctoPetShop; User ID=sa; Password=#{Project.SQLServer.SA.Password}"