apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- namespace.yaml

images:
 - name: roberterez/octopetshop-database
   newTag: #{Octopus.Action.Package[octopetshop.database].Image}

 - name: roberterez/octopetshop-web
   newTag: #{Octopus.Action.Package[octopetshop.web].Image}

 - name: roberterez/octopetshop-shoppingcartservice
   newTag:  #{Octopus.Action.Package[octopetshop.shoppingcartservice].Image}

 - name: roberterez/octopetshop-productservice
   newTag:  #{Octopus.Action.Package[octopetshop.productservice].Image}

patches:
  - target:
      kind: Deployment
      name: octopetshop-web-deployment
    path: octopetshop-web-deployment.yaml