apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base


images:
 - name: productservice
   newName: roberterez/octopussamples.octopetshop.productservice
   newTag: 20240611.033140-master

patches:
  - target:
      kind: Deployment
      name: octopetshop-web-deployment
    path: octopetshop-web-deployment.yaml
  - target:
      kind: Service
      name: web-loadbalancer
    path: octopetshop-loadbalancer.yaml
  - target:
      kind: Service
      name: octopetshop-web-cluster-ip-service
    path: octopetshop-web-cluster-ip-service.yaml
