apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
#- namespace.yaml

images:
 - name: roberterez/octopetshop-database
   #newName: roberterez/octopussamples.octopetshop.database
   newTag: 20240611.033140-master

 - name: roberterez/octopetshop-web
   #newName: roberterez/octopussamples.octopetshop.web
   newTag: 20240611.033140-master

 - name: roberterez/octopetshop-shoppingcartservice
   #newName: roberterez/octopetshop-shoppingcartservice
   newTag: 20240611.033140-master

 - name: roberterez/octopetshop-productservice
   #newName: roberterez/octopetshop-productservice
   newTag: 20240611.033140-master

patches:
  - target:
      kind: Deployment
      name: octopetshop-web-deployment
    path: octopetshop-web-deployment.yaml